RDKCOM-1233: REFPLTV-447: cpuproc analyzer: resolve -fpermissive error
| ../git/cpuproc_analyzer.cpp:649:39: error: ISO C++ forbids
 comparison between pointer and integer [-fpermissive]
|   649 |                     while(char_array!='\0')
Reason for change: gcc 9.2 throws -fpermissive error
Test Procedure: build and test cpuprocanalyzer
Risks: None
Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>
REFPLTV-447: link pthread to resolve link error
Reason for change: resolving linking error
Test Procedure: build cpuprocanalyzer
Risks: None
Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>

(cherry picked from commit 4c658a2c5c4e8fc33907a0d194788fe40dfe610b)
Change-Id: Ie2e92346b20fc09c90e4d2175c510ed0f890abc9